server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Fallback pour Single Page Application
    location / {
        try_files $uri /index.html;
    }

    # Les fichiers statiques (js, css, images) sont servis normalement
    location /assets/ {
        try_files $uri =404;
    }
}